const el=id=>document.getElementById(id), fmt=n=>new Intl.NumberFormat('ru-RU').format(n);
let revision=0,map,layer;
if(window.L){map=L.map('map').setView([55.75,37.62],10);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:18}).addTo(map);layer=L.layerGroup().addTo(map);}
async function get(url){const r=await fetch(url);if(!r.ok){const e=await r.json();throw Error(typeof e.detail==='string'?e.detail:JSON.stringify(e.detail));}return r.json();}
function query(){const q=new URLSearchParams({start:el('start').value,end:el('end').value,aggregation:el('aggregation').value,weather_factor:el('weather').value,event_factor:el('event').value,season_factor:el('season').value});if(el('route').value)q.set('routes',el('route').value);return q;}
async function update(){const n=++revision;el('error').textContent='';try{const q=query(),d=await get('/v1/forecast?'+q);if(n!==revision)return;el('total').textContent=fmt(d.total);el('comparison').textContent=`Базовый прогноз: ${fmt(d.baseline_total)}. ${d.scenario?'Показан сценарий с поправками.':'Коэффициенты не применены.'}`;el('download').href='/v1/forecast.csv?'+q;el('rows').replaceChildren();for(const r of d.rows.slice(0,100)){const tr=document.createElement('tr');for(const value of [r.route,(r.date||r.month||'')+(r.hour===undefined?'':` ${String(r.hour).padStart(2,'0')}:00`),fmt(r.prediction)]){const td=document.createElement('td');td.textContent=value;tr.append(td);}el('rows').append(tr);}
 const sums=new Map();for(const r of d.rows){const k=(r.date||r.month||'')+(r.hour===undefined?'':` ${String(r.hour).padStart(2,'0')}:00`);sums.set(k,(sums.get(k)||0)+r.prediction);}const points=[...sums.entries()].sort((a,b)=>a[0].localeCompare(b[0])),max=Math.max(1,...points.map(p=>p[1]));el('chart').replaceChildren();const line=document.createElementNS('http://www.w3.org/2000/svg','polyline');line.setAttribute('points',points.map((p,i)=>`${20+i*500/Math.max(1,points.length-1)},${200-p[1]*180/max}`).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#087b69');line.setAttribute('stroke-width','3');el('chart').append(line);el('chart-range').textContent=points.length?`${points[0][0]} → ${points[points.length-1][0]}. Пик: ${fmt(max)} посадок.`:'';
 if(map){const suffix=el('route').value?'?route='+el('route').value:'';const [geo,stops]=await Promise.all([get('/v1/geo/routes'+suffix),get('/v1/geo/stops'+suffix)]);if(n!==revision)return;layer.clearLayers();const lines=L.geoJSON(geo,{style:{color:'#087b69',weight:3}}).addTo(layer);for(const s of stops.stops){const t=document.createElement('div');t.textContent=s.name+' · '+s.routes.join(', ')+' · справочная остановка';L.circleMarker([s.lat,s.lon],{radius:3,color:'#244966'}).bindPopup(t).addTo(layer);}if(lines.getBounds().isValid())map.fitBounds(lines.getBounds(),{padding:[15,15]});}
}catch(e){if(n===revision)el('error').textContent=e.message;}}
el('controls').onsubmit=e=>{e.preventDefault();update();};let scenarioTimer;for(const id of ['weather','event','season'])el(id).oninput=()=>{clearTimeout(scenarioTimer);scenarioTimer=setTimeout(update,200);};
el('reset').onclick=()=>{for(const id of ['weather','event','season'])el(id).value=1;update();};el('month').onclick=()=>{el('start').value='2025-11-01';el('end').value='2025-11-30';el('aggregation').value='day';update();};
get('/v1/routes').then(d=>{for(const r of d.routes){const o=document.createElement('option');o.value=r.route;o.textContent=r.name;el('route').append(o);}return update();}).catch(e=>el('error').textContent=e.message);
